# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [1]:
import numpy as np

num_array= np.arange(1, 11)
num_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
``

In [2]:
num_zeros=np.array([[0, 0, 0], [0, 0, 0],[0, 0, 0]])
num_zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
num_ze=np.zeros((3, 3))
num_ze

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

`

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

In [4]:
array_ev=np.linspace(0,5,10)
array_ev

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

In [5]:
num_matrix=np.identity(5)
num_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

In [6]:
num_m=np.random.rand(4,4)
num_m

array([[0.20385235, 0.0839663 , 0.03610123, 0.03414571],
       [0.7530897 , 0.71327608, 0.46591253, 0.36079494],
       [0.52830693, 0.1030393 , 0.51723537, 0.25842937],
       [0.67872626, 0.76644187, 0.63876005, 0.30441899]])

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

In [7]:
num_m.shape

(4, 4)

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

In [8]:
num_arr=np.arange(1,17)
num_arr.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

In [9]:
arry = np.array([1, 2, 3], dtype=np.int32)
print(arry)
arry2 = np.array([1, 2, 3], dtype=np.int64)
print(arry2)
print(arry.dtype)
print(arry.nbytes)
print(arry2.nbytes)

[1 2 3]
[1 2 3]
int32
12
24


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

In [10]:
num_inte=np.arange(1,101)
num_inte2=num_inte[num_inte % 2 ==0]
print(num_inte2)


[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

In [11]:
ran=np.random.randint(10,50,size=(6, 6))
ran

array([[45, 19, 16, 29, 27, 15],
       [48, 31, 12, 31, 49, 37],
       [23, 43, 24, 12, 16, 30],
       [35, 35, 38, 25, 16, 27],
       [45, 45, 18, 10, 31, 25],
       [29, 46, 41, 34, 44, 23]])

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

In [12]:
si_ran=ran[2:5, 2:5]
si_ran


array([[24, 12, 16],
       [38, 25, 16],
       [18, 10, 31]])

In [13]:
ran=np.random.randint(10,50,size=(6, 6))
ran1=ran[0:3, 0:3]
ran1

array([[22, 16, 45],
       [31, 33, 16],
       [42, 23, 37]])

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

In [14]:
num_inte=np.arange(1,101)
np.sum(num_inte)

5050

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

In [15]:
num_inte=np.arange(1,101)
a=np.mean(num_inte)
print(a)
b=np.median(num_inte)
print(b)
c=np.std(num_inte)
print(c)

50.5
50.5
28.86607004772212


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

In [16]:
num_inte=np.random.randint(1,101, size=(5,5))
np.max(num_inte, axis=0)

array([98, 96, 84, 99, 87])

In [17]:
num_inte=np.random.randint(1,101, size=(5,5))
np.max(num_inte, axis=1)

array([89, 99, 95, 95, 69])

In [18]:
num_inte=np.random.randint(1,101, size=(5,5))
np.min(num_inte, axis=1)

array([20, 12,  9,  2, 12])

In [19]:
num_inte=np.random.randint(1,101, size=(5,5))
np.min(num_inte, axis=0)

array([13,  1,  6,  9, 14])

In [20]:
num_inte=np.random.randint(1,101, size=(5,5))
np.min(num_inte)

3

In [21]:
num_inte=np.random.randint(1,101, size=(5,5))
np.max(num_inte)

100

---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

In [22]:
integers = np.random.randint(200, size=20)
print(integers)
v=np.argmax(integers)
print(v)

[124  86  65 180 175  13 199  77 117  84 158 172 115  91 125 166 182 101
 153 137]
6


---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

In [23]:
pet=np.arange(21)
print(pet)
pet1=pet[::-1]
print(pet1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

In [24]:
mat_arr=np.random.randint(10, size=(3,3))
print(mat_arr)
mat_arr1=np.random.randint(10, size=(3,3))
print(mat_arr1)
mat_malt=np.multiply(mat_arr,mat_arr1)
print(mat_malt)

[[0 7 2]
 [8 4 5]
 [7 3 6]]
[[0 1 3]
 [0 9 9]
 [0 5 2]]
[[ 0  7  6]
 [ 0 36 45]
 [ 0 15 12]]


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

In [25]:
pet=np.arange(3)
np.diag(pet)

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

In [26]:
alb = np.array([[1,2,3,4], [5,6,7,8]])
alb1 = np.array([[4,5,8,9], [9,10,11,12]])
bab=np.multiply(alb,alb1)
print(bab)

[[ 4 10 24 36]
 [45 60 77 96]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

In [27]:
alb.flatten()


array([1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.ndarray.flatten(alb)

array([1, 2, 3, 4, 5, 6, 7, 8])

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

In [29]:
alti=np.arange(6)
altii=np.arange(6)
beet=np.vstack((alti,altii))
print(beet)

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]]


---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

In [30]:
beet2=np.hstack((alti,altii))
print(beet2)

[0 1 2 3 4 5 0 1 2 3 4 5]


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

In [31]:
import numpy as np
arup=np.random.randint(1,36, size=(6, 6))
np.split(arup,2)                     

[array([[16,  5, 32, 20, 16,  1],
        [33, 18,  6,  6,  9, 27],
        [11, 20, 31, 25, 34, 14]]),
 array([[31, 31, 34, 23, 19, 19],
        [19,  3, 35,  4,  8, 16],
        [ 8, 24,  9, 31,  9, 19]])]

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

In [32]:
import numpy as np

biz=np.random.rand(1,10)
biz_rounded=np.round(biz, 2)
print(biz_rounded)

[[0.6  0.56 0.5  0.95 0.98 0.91 0.87 0.51 0.06 0.38]]


---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

In [33]:
tet=np.array([2,3,4,5,7,1,2])
np.unique(tet)

array([1, 2, 3, 4, 5, 7])

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

In [34]:
arv = np.array([10, 2, 13, 10, 9, 5, 0, 8])
value = 5
arv[arv < value] = value
print(arv)

[10  5 13 10  9  5  5  8]


---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

In [35]:
arv = np.array([10, 2, 13, 10, 9, 5, 0, 8])

np.cumsum(arv)

array([10, 12, 25, 35, 44, 49, 49, 57])

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

In [36]:
arv1 = np.array([10, 2, 0, 0, 9, 5, 0, 8])


np.count_nonzero(arv1)

5

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

In [37]:
tin = np.random.randint(0, 50,10)
np.sort(tin)

array([ 3,  6, 11, 18, 22, 26, 29, 34, 44, 45])

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

In [38]:
arup=np.random.randint(1,9, size=(3, 3))
print(np.sum(arup, axis=1))
print(np.sum(arup, axis=0))

[16 20 10]
[20 14 12]


---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

In [39]:
zin = np.random.rand(2, 2) * 10
normalized=(zin-np.max(zin))/(np.max(zin)-np.min(zin))
print(normalized)

[[-0.57195232  0.        ]
 [-1.         -0.54245715]]


---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

In [40]:
x=np.array([10,20,13,4])
y=np.array([12,14,51,17])

z=np.dot(x,y)
print(z)

1131


---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

In [41]:
arup=np.random.randint(1,9, size=(3, 3))

np.trace(arup)

7

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

In [42]:
arup=np.random.randint(1,4, size=(2, 2))


arup[[0, 1]] = arup[[1, 0]]
print(arup)

[[2 1]
 [1 2]]


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

In [43]:
vec=np.array([12,33,14,15])
print(vec.reshape(-1,1))

[[12]
 [33]
 [14]
 [15]]


---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

In [44]:
arup=np.random.randint(1,9, size=(3, 3))

print( np.linalg.det(arup))

57.999999999999986


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---